openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://taskmanager.test'
paths:
  /api/user/register:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: koctjmdwzbajrtnsbnnmpggqqxcmhlqzcpetwntdfgttkcvsixubpbpgpsakcdhjqsgtjspjlhzyghlw
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: karianne74@example.org
                password:
                  type: string
                  description: 'Must be at least 4 characters.'
                  example: ''
              required:
                - name
                - email
                - password
      security: []
  /api/user/login:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: glcngkgsvpgpchraaxwtrsdqredpsczpbkzktfcfxcaocqvmiekogwtkeflzkupofgvchkkctpoxhkvsndnwzfbxeadumrstvnrjgudgorndfrsqxeutrmixpomknablqlhsakkwrzwnaneotiatsxwrahdeyynukxvktzphyfgvjhugmamiiirinx
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: eda02@example.com
                password:
                  type: string
                  description: 'Must be at least 4 characters.'
                  example: tqw
              required:
                - name
                - email
                - password
      security: []
  /api/taskmanager/users:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/taskmanager/user/update/{id}':
    put:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must be at least 1 characters.'
                  example: ''
                description:
                  type: string
                  description: ''
                  example: omnis
                category:
                  type: string
                  description: ''
                  example: ipsa
                completed:
                  type: boolean
                  description: ''
                  example: true
                name:
                  type: string
                  description: 'Must be at least 4 characters.'
                  example: ar
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: culpa
        required: true
        schema:
          type: string
  /api/taskmanager/user/profile:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/taskmanager/user/show/{id}':
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the show.'
        example: illo
        required: true
        schema:
          type: string
  /api/taskmanager/user/logout:
    post:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/taskmanager/tasks:
    get:
      summary: 'Display a listing of the resource.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  '/api/taskmanager/task/show/{id}':
    get:
      summary: 'Display the specified resource.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the show.'
        example: vel
        required: true
        schema:
          type: string
  /api/taskmanager/task/create:
    post:
      summary: 'Store a newly created resource in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must be at least 1 characters.'
                  example: v
                description:
                  type: string
                  description: ''
                  example: exercitationem
                category:
                  type: string
                  description: ''
                  example: eum
                completed:
                  type: boolean
                  description: ''
                  example: false
              required:
                - title
                - category
                - completed
      security: []
  '/api/taskmanager/task/update/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must be at least 1 characters.'
                  example: ''
                description:
                  type: string
                  description: ''
                  example: est
                category:
                  type: string
                  description: ''
                  example: aliquid
                completed:
                  type: boolean
                  description: ''
                  example: false
              required:
                - title
                - category
                - completed
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: exercitationem
        required: true
        schema:
          type: string
  '/api/taskmanager/task/delete/{id}':
    delete:
      summary: 'Remove the specified resource from storage.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the delete.'
        example: ipsam
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
